import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {root} from './cdp.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,''));
const problems=[],files=[];
const walk=dir=>fs.readdirSync(path.join(root,dir),{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.posix.join(dir,e.name)):[path.posix.join(dir,e.name)]);
function jpeg(b){if(b.readUInt16BE(0)!==0xffd8||b.readUInt16BE(b.length-2)!==0xffd9)throw Error('Invalid/incomplete JPEG');let p=2;while(p<b.length-4){if(b[p]!==255){p++;continue;}while(b[p]===255)p++;const m=b[p++];if(m===0xd9||m===0xda)break;const n=b.readUInt16BE(p);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(m))return {width:b.readUInt16BE(p+5),height:b.readUInt16BE(p+3)};p+=n;}throw Error('JPEG dimensions missing')}
const conditions=new Map(read('observations/E-070-capture-conditions.json').map(x=>[x.file,x]));
const epochs=read('observations/E-060-loader-timeline.json');
const docs=read('observations/E-085-facts-timeline.json');
const excluded=['observations/artifact-manifest.json','observations/artifact-index.md','observations/package-verification.json'];
for(const rel of ['reference-evidence.md',...walk('captures'),...walk('observations'),...walk('helpers')].filter(p=>!excluded.includes(p))){
 const b=fs.readFileSync(path.join(root,rel)),stat=fs.statSync(path.join(root,rel)),stem=path.basename(rel,path.extname(rel));
 const item={evidenceId:stem.startsWith('E-')?stem:rel.startsWith('helpers/')?'H-'+stem:'PKG-MAIN',path:rel,bytes:b.length,sha256:sha(b),fileTimestampUTC:stat.mtime.toISOString(),timestampCairo:new Date(stat.mtimeMs+10800000).toISOString().replace('Z','+03:00'),source:stem.match(/^E-(001|004|005|006|007|008|009|010)$/)?'S-01/S-03':stem==='E-020-tool-capabilities'?'tool capability evidence':rel.startsWith('helpers/')?'task-written capture helper':'S-02',method:rel.endsWith('.jpg')?'Original browser JPEG screenshot':rel.endsWith('.json')?'Sanitized browser/tool observation or task metadata':'Written evidence contract/helper',modified:stem.startsWith('E-081'),conditionEvidence:[]};
 try{if(rel.endsWith('.json'))read(rel);if(rel.endsWith('.jpg'))item.image=jpeg(b);}catch(e){problems.push({file:rel,reason:e.message})}
 if(conditions.has(rel)){item.conditions=conditions.get(rel);item.conditionEvidence=['observations/E-070-capture-conditions.json'];}
 else if(rel.startsWith('captures/E-030-')){const label=stem.match(/E-030-(\d+x\d+)/)[1];item.conditions={environment:read('observations/E-030-'+label+'-geometry.json').environment,scroll:'See named state and scroll recipe; exact individual capture scroll not independently recorded',readiness:'Early/transitional capture, use E-070 for settled acceptance'};item.conditionEvidence=['observations/E-030-'+label+'-geometry.json','observations/E-030-'+label+'-scroll.json'];}
 else if(rel.startsWith('captures/E-060-')){const m=stem.match(/E-060-loader-(normal|reduced)-(\d+)/);const e=epochs.find(x=>x.reduced===(m[1]==='reduced'));item.conditions={environment:e.environment,state:e.frames[Number(m[2])-1].state};item.conditionEvidence=['observations/E-060-loader-timeline.json'];}
 else if(rel.startsWith('captures/E-085-')){const n=Number(stem.match(/(\d+)$/)[1]);item.conditions=docs[n-1];item.conditionEvidence=['observations/E-085-facts-timeline.json'];}
 else if(rel.endsWith('.jpg')){item.conditions={environment:stem.startsWith('E-004')||stem.startsWith('E-010')?'ENV-P':'ENV-C; named size/preference in filename or companion observation',scroll:'Consult matching observation/journey and replay recipe; do not infer behavior from screenshot alone',timeOrigin:'File timestamp records capture save; temporal sets include performance timestamps'};if(stem.startsWith('E-040'))item.conditionEvidence=['observations/E-040-boundaries.json'];else if(stem.startsWith('E-041'))item.conditionEvidence=['observations/E-041-preferences-height.json'];else if(stem.startsWith('E-050')||stem.startsWith('E-051')||stem.startsWith('E-052')||stem.startsWith('E-053'))item.conditionEvidence=['observations/E-050-1440-journeys.json','observations/E-050-390-journeys.json'];else if(stem.startsWith('E-061'))item.conditionEvidence=['observations/E-061-settled-desktop.json'];else if(stem.startsWith('E-062')||stem.startsWith('E-063'))item.conditionEvidence=['observations/E-062-distinctive-motion.json'];else if(stem.startsWith('E-080'))item.conditionEvidence=['observations/E-080-reversal-focus-ufo.json'];else if(stem.startsWith('E-081'))item.conditionEvidence=['observations/E-081-simulated-widget-failure.json'];else if(stem.startsWith('E-086'))item.conditionEvidence=['observations/E-086-preview-query.json'];else if(stem.startsWith('E-090'))item.conditionEvidence=['observations/E-090-faq-keyboard.json'];}
 files.push(item);
}
const stamp=new Date().toISOString();
fs.writeFileSync(path.join(root,'observations/artifact-manifest.json'),JSON.stringify({package:'HBC-2026-10-04',revision:'1.0.0',frozenAtUTC:stamp,timeZone:'Africa/Cairo',excludedSelfReferentialMetadata:excluded,files},null,2));
const rows=files.map(f=>'| '+f.evidenceId+' | ['+f.path+'](../'+f.path+') | '+f.timestampCairo+' | '+(f.image?f.image.width+'x'+f.image.height:'')+' | '+(f.modified?'INDUCED FAILURE':'original/read-only evidence')+' |').join('\n');
fs.writeFileSync(path.join(root,'observations/artifact-index.md'),'# Artifact index\n\nPackage HBC-2026-10-04, revision 1.0.0. Exact SHA-256 hashes, provenance and conditions are in [artifact-manifest.json](artifact-manifest.json). Final settled scenes are E-070; early context and temporal captures remain preserved.\n\n| Evidence ID | Artifact | Save time Africa/Cairo | Image pixels | Disposition |\n| --- | --- | --- | --- | --- |\n'+rows+'\n');
let linkCount=0;
for(const rel of ['reference-evidence.md','helpers/README.md','observations/artifact-index.md']){
 const text=fs.readFileSync(path.join(root,rel),'utf8');
 for(const m of text.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)){const href=m[1];if(/^(https?:|#)/.test(href))continue;linkCount++;const dest=path.resolve(path.dirname(path.join(root,rel)),href.split('#')[0]);if(!dest.startsWith(root+path.sep)&&dest!==root)problems.push({file:rel,link:href,reason:'Link leaves package'});else if(!fs.existsSync(dest)&&!dest.endsWith('package-verification.json'))problems.push({file:rel,link:href,reason:'Missing link target'});}
}
const text=fs.readFileSync(path.join(root,'reference-evidence.md'),'utf8');
for(const h of ['Package identity and scope','Canonical directory layout','Source register and precedence','Environment and reset recipes','Artifact manifest','Routes, components and state graph','Design and layout contract','Typography','Assets','Responsive contract','Behavior and accessibility contract','Motion contract','Runtime/data contract','Tool decisions and escalation','Uncertainty and conflict register','Coverage matrix','Acceptance seeds','Pre-implementation gate record','Revision record'])if(!text.includes(h))problems.push({reason:'Missing canonical section',section:h});
if(!text.includes('Decision: **BLOCKED**'))problems.push({reason:'Incorrect gate decision'});
for(const f of files)if(sha(fs.readFileSync(path.join(root,f.path)))!==f.sha256)problems.push({file:f.path,reason:'Hash mismatch'});
const report={package:'HBC-2026-10-04',revision:'1.0.0',checkedAtUTC:new Date().toISOString(),checkedAtCairo:new Date(Date.now()+10800000).toISOString().replace('Z','+03:00'),checks:{jsonParse:'performed',jpegStructureDimensionsAndEndMarker:'performed',sha256Replay:'performed',relativeLinks:'performed',canonicalSections:'performed',gateHonesty:'BLOCKED; U-01/U-02 not waived'},counts:{files:files.length,json:files.filter(f=>f.path.endsWith('.json')).length,images:files.filter(f=>f.image).length,relativeLinks:linkCount},manifestSHA256:sha(fs.readFileSync(path.join(root,'observations/artifact-manifest.json'))),indexSHA256:sha(fs.readFileSync(path.join(root,'observations/artifact-index.md'))),problems,notRun:['Implementation tests','Reconstruction visual acceptance','Physical device or assistive technology testing'],result:problems.length?'FAIL':'PASS'};
fs.writeFileSync(path.join(root,'observations/package-verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(problems.length)process.exitCode=1;
