from pathlib import Path
p=Path('skills/reference-reconstruction/scripts/page-probe.js');s=p.read_text(encoding='utf-8-sig')
s=s.replace("const r=rect(node),belongs=policy.scope!=='region'||regionNodes.some(root=>root===node||root.contains(node));\n        if(belongs&&(policy.scope==='full-page'||intersects(r,scopeRect)))", "const r=rect(node),belongs=policy.scope!=='region'||regionNodes.some(root=>root===node||root.contains(node));\n        const scopeAncestor=policy.scope==='region'&&regionNodes.some(root=>node!==root&&node.contains(root));\n        if(scopeAncestor||(belongs&&(policy.scope==='full-page'||intersects(r,scopeRect))))")
p.write_text(s,encoding='utf-8')
p=Path('skills/reference-reconstruction/scripts/test-settled-appearance.mjs');s=p.read_text(encoding='utf-8-sig')
s=s.replace("import path from 'node:path';","import path from 'node:path';\nimport os from 'node:os';")
s=s.replace('{waitReady,validatePlan}', '{waitReady,validatePlan,capture}')
s=s.replace("    '/transition':base", "    '/ancestor':base({css:'#ancestor{opacity:0;animation:parentReveal 250ms 500ms forwards}@keyframes parentReveal{to{opacity:1}}',html:'<section id=\"ancestor\"><main><div id=\"child\">Nested region</div></main></section>'}),\n    '/transition':base")
needle="    await t.test('classified ambient motion"
idx=s.index(needle)
s=s[:idx]+"    await t.test('region readiness includes ancestors with delayed finite motion',async()=>{\n      const r=await run('/ancestor',checkpoint({appearance:{scope:'region',selector:'main'}}));assert.equal(r.status,'settled');assert.ok(r.elapsedMs>=750);assert.ok(r.appearance.samples.some(s=>s.reasons.some(reason=>reason.startsWith('finite-motion:'))));\n    });\n"+s[idx:]
needle='  } finally {\n    if(context)'
idx=s.index(needle)
s=s[:idx]+"    await t.test('screenshot pixel refusal invalidates successful viewport appearance',async()=>{\n      const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reference-appearance-test-'));\n      try {\n        const plan=JSON.parse(fs.readFileSync(new URL('../assets/capture-plan.example.json',import.meta.url),'utf8'));\n        const origin='http://127.0.0.1:'+server.address().port;plan.allowedOrigins=[origin];plan.browserChannel=process.env.REFERENCE_BROWSER_CHANNEL||'chrome';plan.environments[0].viewport={width:8000,height:8000};\n        plan.cases=[{id:'PIXEL',environmentId:'ENV-D',url:origin+'/static',state:'Stable but no screenshot',reset:'fresh-context',checkpoints:[checkpoint()]}];\n        const output=path.join(dir,'run'),r=await capture(plan,output,modulePath);assert.equal(r.result,'INCOMPLETE');\n        const record=JSON.parse(fs.readFileSync(path.join(output,'PIXEL--STATE.json'),'utf8'));assert.equal(record.phase,'unsettled');assert.equal(record.readiness.appearance.state,'unresolved');assert.equal(record.readiness.appearance.convergence.pass,false);assert.ok(record.readiness.reasons.includes('capture-pixel-budget-exceeded'));assert.ok(!record.screenshot);\n      } finally {if(path.dirname(path.resolve(dir))!==path.resolve(os.tmpdir())||!path.basename(dir).startsWith('reference-appearance-test-'))throw Error('Unexpected cleanup target');fs.rmSync(dir,{recursive:true,force:true});}\n    });\n"+s[idx:]
p.write_text(s,encoding='utf-8')
