from pathlib import Path
p=Path('skills/reference-reconstruction/scripts/settled-appearance.mjs');s=p.read_text(encoding='utf-8-sig')
s=s.replace('async function visualSample(page,snapshot,p,remaining) {','export async function visualSample(page,snapshot,p,remaining) {')
s=s.replace('  if(p.ambient.length) {','  const env=snapshot.environment;\n  const area=options.clip?options.clip.width*options.clip.height:env.cssViewport.width*env.cssViewport.height;\n  if(area*env.dpr**2>30_000_000) throw Error("visual sample pixel budget exceeded");\n  if(p.ambient.length) {')
s=s.replace('lastVisual=null;','lastVisual=null,priorSignals=null;')
s=s.replace("      const signature=JSON.stringify([sample.geometrySignature,p.mode==='geometry-only'?null:appearanceSignature(snapshot),visual?.sha256||null]);", "      const signals={geometry:sample.geometrySignature,appearance:p.mode==='geometry-only'?null:appearanceSignature(snapshot),visual:visual?.sha256||null};\n      sample.changedSignals=priorSignals?Object.keys(signals).filter(k=>signals[k]!==priorSignals[k]):['initial-sample'];\n      priorSignals=signals;\n      const signature=JSON.stringify(signals);")
s=s.replace('streak=0;stableSince=null;prior=null;','streak=0;stableSince=null;prior=null;priorSignals=null;')
p.write_text(s,encoding='utf-8')
p=Path('skills/reference-reconstruction/scripts/capture.mjs');s=p.read_text(encoding='utf-8-sig')
s=s.replace('waitAppearance,postAppearanceReasons}', 'waitAppearance,postAppearanceReasons,visualSample}')
s=s.replace("            const appearanceChanged=cp.phase==='settled'?postAppearanceReasons(before,record.after,cp):[];", "            const appearanceChanged=cp.phase==='settled'?postAppearanceReasons(before,record.after,cp):[];\n            const policy=appearancePolicy(cp);\n            if(cp.phase==='settled'&&policy.visual&&policy.mode==='appearance'&&readiness.appearance.convergence.visual) {\n              record.postVisual=await visualSample(page,record.after,policy,3000);\n              if(record.postVisual.sha256!==readiness.appearance.convergence.visual.sha256) appearanceChanged.push('visual-changed-during-screenshot');\n            }")
p.write_text(s,encoding='utf-8')
p=Path('skills/reference-reconstruction/scripts/test-settled-appearance.mjs');s=p.read_text(encoding='utf-8-sig')
s=s.replace("css:'#child{animation:ambient 2s linear infinite}","css:'#ambient{width:120px;height:120px;overflow:hidden}#child{animation:ambient 2s linear infinite}")
s=s.replace("html:'<main><div id=\"child\">Ambient</div></main>'", "html:'<main><section id=\"ambient\"><div id=\"child\">Ambient</div></section></main>'")
s=s.replace("selector:'#child',properties:['transform'],reason:'Continuous decorative rotation", "selector:'#ambient',properties:['transform'],reason:'Continuous decorative rotation")
s=s.replace("maskedSelectors,['#child']", "maskedSelectors,['#ambient']")
p.write_text(s,encoding='utf-8')
p=Path('skills/reference-reconstruction/references/settled-appearance.md');s=p.read_text(encoding='utf-8-sig').replace('only in diagnostic comparison images','only in diagnostic comparison images').replace('Exact consecutive PNG byte hashes','Select a stable bounded ambient wrapper when using masks: a moving transformed mask rectangle itself produces changing pixels and must not be force-passed. Exact consecutive PNG byte hashes');p.write_text(s,encoding='utf-8')
