import {connect} from './cdp.mjs';const c=await connect();const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function key(key,code,modifiers=0){for(const type of ['keyDown','keyUp'])await c.call('Input.dispatchKeyEvent',{type,key,windowsVirtualKeyCode:code,modifiers})}
async function click(selector){const r=await c.evaluate('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');e.scrollIntoView({block:"center",behavior:"instant"});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');await c.call('Input.dispatchMouseEvent',{type:'mouseMoved',...r});for(const type of ['mousePressed','mouseReleased'])await c.call('Input.dispatchMouseEvent',{type,...r,button:'left',clickCount:1})}
const state=()=>c.evaluate("({timestamp:new Date().toISOString(),perf:performance.now(),scrollY,focus:{tag:document.activeElement.tagName,cls:document.activeElement.className,text:document.activeElement.innerText?.slice(0,90)},root:document.documentElement.className,menuHidden:document.querySelector('.site-nav').hidden,menuOpen:document.querySelector('.site-nav').classList.contains('is-open'),modalHidden:document.querySelector('.ticket-modal').hidden,modalOpen:document.querySelector('.ticket-modal').classList.contains('is-open'),fallbackHidden:document.querySelector('.ticket-modal-fallback').hidden,statusHidden:document.querySelector('.ticket-modal-status').hidden,track:getComputedStyle(document.querySelector('.story-track')).transform,count:document.querySelector('.story-count').innerText,video:[...document.querySelectorAll('video')].map(v=>({src:v.currentSrc,currentTime:v.currentTime,duration:v.duration,readyState:v.readyState,seeking:v.seeking})),details:[...document.querySelectorAll('details')].map(d=>({open:d.open,height:d.getBoundingClientRect().height})),animations:document.getAnimations().filter(a=>a.playState==='running').map(a=>({name:a.animationName,duration:a.effect.getComputedTiming().duration,currentTime:a.currentTime}))})");
try{
await c.call('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});await c.call('Emulation.setTouchEmulationEnabled',{enabled:false,maxTouchPoints:1});await c.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await c.call('Page.navigate',{url:'https://www.hauntedbouldercity.com/'});await sleep(4000);
const log=[];const record=async(action)=>log.push({action,state:await state()});
await click('.menu-toggle');for(let i=0;i<12;i++){await key('Tab',9);await record('menu Tab '+i)}await key('Escape',27);await click('.menu-toggle');await sleep(100);await click('.menu-toggle');await sleep(100);await click('.menu-toggle');await sleep(750);await record('rapid menu reversal');await key('Escape',27);await sleep(650);
await click('.faq details:first-child summary');await sleep(100);await click('.faq details:first-child summary');await sleep(500);await record('FAQ interruption closes');
await c.evaluate("document.querySelector('#stories').scrollIntoView({behavior:'instant'})");await sleep(1500);const s=await c.evaluate("(()=>{const e=document.querySelector('#stories');return {top:e.getBoundingClientRect().top+scrollY,travel:e.offsetHeight-innerHeight}})()");
for(const phase of [0,.25,.5,.65,.8,1,.8,.5]){await c.evaluate('scrollTo({top:'+Math.round(s.top+s.travel*phase)+',behavior:"instant"})');await sleep(500);await record('fresh normal UFO phase '+phase);if(phase>=.65)await c.shot('captures/E-080-ufo-'+phase+'-'+log.length+'.jpg')}
await click('.button-large');await sleep(11000);for(let i=0;i<8;i++){await key('Tab',9);await record('modal Tab '+i)}await c.call('Input.dispatchMouseEvent',{type:'mousePressed',x:20,y:20,button:'left',clickCount:1});await c.call('Input.dispatchMouseEvent',{type:'mouseReleased',x:20,y:20,button:'left',clickCount:1});await sleep(600);await record('outside veil close');c.save('observations/E-080-reversal-focus-ufo.json',{environment:await c.env(),log});
await c.call('Network.enable');await c.call('Network.setBlockedURLs',{urls:['https://www.eventbrite.com/static/widgets/eb_widgets.js']});await c.call('Page.navigate',{url:'https://www.hauntedbouldercity.com/'});await sleep(4000);await click('.button-large');await sleep(1100);await c.shot('captures/E-081-simulated-widget-failure.jpg');c.save('observations/E-081-simulated-widget-failure.json',{environment:await c.env(),modification:'Network.setBlockedURLs blocks only public Eventbrite widget script; induced reference failure, not naturally observed service failure',state:await state()});await key('Escape',27);await c.call('Network.setBlockedURLs',{urls:[]});
console.log('fresh UFO, focus wrap, reversal, controlled failure captured');
}finally{await c.call('Emulation.clearDeviceMetricsOverride');await c.call('Emulation.setTouchEmulationEnabled',{enabled:false,maxTouchPoints:1});await c.call('Emulation.setEmulatedMedia',{features:[]});c.close()}
