import {connect} from './cdp.mjs';const c=await connect();const sleep=ms=>new Promise(r=>setTimeout(r,ms));const traffic=[],consoleErrors=[];c.onEvent(m=>{const p=m.params;if(m.method==='Network.requestWillBeSent'){const u=new URL(p.request.url);if(['www.hauntedbouldercity.com','www.eventbrite.com'].includes(u.hostname))traffic.push({t:p.timestamp,requestId:p.requestId,kind:'request',method:p.request.method,host:u.hostname,path:u.pathname,queryKeys:[...u.searchParams.keys()],type:p.type})}if(m.method==='Network.responseReceived')traffic.push({t:p.timestamp,requestId:p.requestId,kind:'response',status:p.response.status,type:p.type,mime:p.response.mimeType});if(m.method==='Network.loadingFailed')traffic.push({t:p.timestamp,requestId:p.requestId,kind:'failure',type:p.type,error:p.errorText});if(m.method==='Runtime.exceptionThrown')consoleErrors.push({time:p.timestamp,text:p.exceptionDetails.text})});
await c.call('Network.enable');await c.call('Runtime.enable');
const state=()=>c.evaluate("({timestamp:new Date().toISOString(),perf:performance.now(),url:location.href,scrollY,root:document.documentElement.className,focus:{tag:document.activeElement.tagName,cls:document.activeElement.className,text:document.activeElement.innerText?.slice(0,120)},menu:{hidden:document.querySelector('.site-nav').hidden,open:document.querySelector('.site-nav').classList.contains('is-open'),expanded:document.querySelector('.menu-toggle').getAttribute('aria-expanded'),opacity:getComputedStyle(document.querySelector('.site-nav')).opacity},modal:{hidden:document.querySelector('.ticket-modal').hidden,open:document.querySelector('.ticket-modal').classList.contains('is-open'),opacity:getComputedStyle(document.querySelector('.ticket-modal')).opacity,statusHidden:document.querySelector('.ticket-modal-status').hidden,fallbackHidden:document.querySelector('.ticket-modal-fallback').hidden,frames:[...document.querySelectorAll('.ticket-modal iframe')].map(f=>({title:f.title,srcHost:new URL(f.src).hostname,path:new URL(f.src).pathname}))},details:[...document.querySelectorAll('details')].map(d=>({open:d.open,height:d.getBoundingClientRect().height})),track:getComputedStyle(document.querySelector('.story-track')).transform,count:document.querySelector('.story-count').innerText,animations:document.getAnimations().filter(a=>a.playState==='running').map(a=>({name:a.animationName,duration:a.effect.getComputedTiming().duration,currentTime:a.currentTime}))})");
const key=async(k,code,modifiers=0)=>{await c.call('Input.dispatchKeyEvent',{type:'keyDown',key:k,windowsVirtualKeyCode:code,modifiers});await c.call('Input.dispatchKeyEvent',{type:'keyUp',key:k,windowsVirtualKeyCode:code,modifiers})};
async function click(selector,mobile=false){const r=await c.evaluate('(()=>{const e=document.querySelector('+JSON.stringify(selector)+');e.scrollIntoView({block:"center",behavior:"instant"});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');if(mobile){await c.call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x,y:r.y,radiusX:1,radiusY:1}]});await c.call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})}else{await c.call('Input.dispatchMouseEvent',{type:'mouseMoved',...r});await c.call('Input.dispatchMouseEvent',{type:'mousePressed',...r,button:'left',clickCount:1});await c.call('Input.dispatchMouseEvent',{type:'mouseReleased',...r,button:'left',clickCount:1})}}
try{const journeys=[];
for(const [w,h,mobile] of [[1440,900,false],[390,844,true]]){
await c.call('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile});await c.call('Emulation.setTouchEmulationEnabled',{enabled:mobile,maxTouchPoints:1});await c.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await c.evaluate("scrollTo({top:0,behavior:'instant'})");await sleep(200);
const log=[],record=async(action)=>log.push({action,state:await state()});
await record('reset');await click('.menu-toggle',mobile);
for(const delay of [0,100,250,450]){await sleep(delay);await record('menu-open after additional '+delay+'ms')}await c.shot('captures/E-050-'+w+'-menu-open.jpg');await key('Tab',9);await record('menu Tab');await key('Tab',9,8);await record('menu Shift+Tab');await key('Escape',27);await sleep(650);await record('menu Escape');await c.shot('captures/E-050-'+w+'-menu-closed-focus.jpg');
await click('.menu-toggle',mobile);await sleep(700);await click('#site-nav a[href="#about"]',mobile);await sleep(2300);await record('menu about navigation');const history=await c.call('Page.getNavigationHistory');if(history.currentIndex>0){await c.call('Page.navigateToHistoryEntry',{entryId:history.entries[history.currentIndex-1].id});await sleep(300);await record('history back');await c.call('Page.navigateToHistoryEntry',{entryId:history.entries[history.currentIndex].id});await sleep(300);await record('history forward')}
for(let i=1;i<=9;i++){await click('.faq details:nth-child('+i+') summary',mobile);await sleep(700);await record('FAQ '+i+' open');if(i===1||i===9)await c.shot('captures/E-051-'+w+'-faq-'+i+'.jpg')}
await click('.faq details:first-child summary',mobile);await sleep(450);await record('FAQ 1 close; remaining answers open');await c.evaluate("document.querySelectorAll('details[open]').forEach(d=>d.open=false)");
if(!mobile){for(const i of [0,1,2,1]){await click('[data-story="'+i+'"]');await sleep(2300);await record('story button '+i);await c.shot('captures/E-052-story-'+i+'-'+log.length+'.jpg')}}
await click('.button-large',mobile);await record('ticket dialog immediate');await c.shot('captures/E-053-'+w+'-ticket-loading.jpg');await sleep(11000);await record('ticket dialog after 11 seconds');await c.shot('captures/E-053-'+w+'-ticket-settled.jpg');await key('Tab',9);await record('ticket Tab');await key('Escape',27);await sleep(550);await record('ticket Escape focus return');await click('.button-large',mobile);await sleep(550);await record('ticket reopen');await click('.ticket-modal-close',mobile);await sleep(550);await record('ticket close button');
journeys.push({environment:await c.env(),input:mobile?'emulated touch and keyboard':'trusted pointer and keyboard',log});
c.save('observations/E-050-'+w+'-journeys.json',journeys[journeys.length-1]);console.log('journeys '+w+' captured');
}
c.save('observations/E-054-network-console.json',{sanitization:'no headers, cookies, bodies, query values, or user session exports',traffic,consoleErrors});
await c.call('DOM.enable');await c.call('CSS.enable');const doc=await c.call('DOM.getDocument');const fonts=[];
for(const selector of ['.haunted-word','.city-word','.section-kicker','.intro p','.faq summary']){const q=await c.call('DOM.querySelector',{nodeId:doc.root.nodeId,selector});fonts.push({selector,result:await c.call('CSS.getPlatformFontsForNode',{nodeId:q.nodeId})})}c.save('observations/E-055-rendered-fonts.json',fonts);c.save('observations/E-056-accessibility.json',await c.call('Accessibility.getFullAXTree'));console.log('network and fonts saved');
}finally{c.close()}
