import fs from 'node:fs';import {connect,root} from './cdp.mjs';const c=await connect();const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const snapshot=()=>c.evaluate("({timestamp:new Date().toISOString(),perf:performance.now(),navigationStart:performance.timeOrigin,root:document.documentElement.className,ready:document.readyState,fonts:document.fonts.status,loader:document.querySelector('.loader')?.className,scrollY,glitch:document.documentElement.classList.contains('is-glitching'),currentTopic:document.querySelector('.topic.is-current')?.dataset.topic,video:[...document.querySelectorAll('video')].map(v=>({src:v.currentSrc,currentTime:v.currentTime,duration:v.duration,readyState:v.readyState,seeking:v.seeking,opacity:getComputedStyle(v).opacity})),layers:[...document.querySelectorAll('.hero h1,.hero-bottom,.nav-panel,.site-nav .fog-wisp,.fog-in-view .fog-wisp,.spirit,.flashlight')].slice(0,18).map(e=>({cls:e.className,opacity:getComputedStyle(e).opacity,transform:getComputedStyle(e).transform,translate:getComputedStyle(e).translate,animation:getComputedStyle(e).animation})),animations:document.getAnimations().filter(a=>a.playState==='running').map(a=>({name:a.animationName,duration:a.effect.getComputedTiming().duration,currentTime:a.currentTime}))})");
try{const sets=[];
for(const reduced of [false,true]){
await c.call('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});await c.call('Emulation.setTouchEmulationEnabled',{enabled:false,maxTouchPoints:1});await c.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:reduced?'reduce':'no-preference'}]});await c.call('Page.navigate',{url:'https://www.hauntedbouldercity.com/'});const frames=[];
for(const delay of [100,300,700,800,1000,1100]){await sleep(delay);frames.push({afterAdditionalMs:delay,state:await snapshot()});await c.shot('captures/E-060-loader-'+(reduced?'reduced':'normal')+'-'+frames.length+'.jpg')}
sets.push({reduced,environment:await c.env(),frames});
}
c.save('observations/E-060-loader-timeline.json',sets);
await c.call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await c.evaluate("scrollTo({top:0,behavior:'instant'})");await sleep(1800);c.save('observations/E-061-settled-desktop.json',{environment:await c.env(),geometry:await c.evaluate(fs.readFileSync(root+'/helpers/measure-function.js','utf8')),readiness:await snapshot()});await c.shot('captures/E-061-settled-desktop-top.jpg');
const motions=[];
for(const sel of ['.tour-facts','.topic[data-topic="guide"]','.button-large']){
await c.evaluate('document.querySelector('+JSON.stringify(sel)+').scrollIntoView({behavior:"instant",block:"center"})');await sleep(100);
const r=await c.evaluate('document.querySelector('+JSON.stringify(sel)+').getBoundingClientRect().toJSON()');await c.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:r.x+r.width/2,y:r.y+r.height/2});const frames=[];
for(const delay of [0,200,400,600,1800]){await sleep(delay);frames.push({afterAdditionalMs:delay,state:await snapshot()});if(delay===200||delay===1800)await c.shot('captures/E-062-'+sel.replace(/[^a-zA-Z]/g,'')+'-'+delay+'.jpg')}motions.push({selector:sel,frames});
}const story=await c.evaluate("(()=>{const e=document.querySelector('#stories');return {top:e.getBoundingClientRect().top+scrollY,travel:e.offsetHeight-innerHeight}})()");
for(const phase of [0,.25,.5,.65,.8,1,.8,.5]){await c.evaluate('scrollTo({top:'+Math.round(story.top+story.travel*phase)+',behavior:"instant"})');await sleep(500);motions.push({storyPhase:phase,state:await snapshot()});if(phase===1||phase===.8)await c.shot('captures/E-063-ufo-phase-'+phase+'-'+motions.length+'.jpg')}
c.save('observations/E-062-distinctive-motion.json',{environment:await c.env(),motions});
const assets=await c.evaluate("async()=>{const out=[];for(const i of document.images){if(i.loading==='lazy')i.scrollIntoView({behavior:'instant',block:'center'});const result=await Promise.race([i.decode().then(()=>({decode:'ok'}),e=>({decode:'failed',error:e.name})),new Promise(r=>setTimeout(()=>r({decode:'timeout'}),2500))]);out.push({src:i.currentSrc,alt:i.alt,complete:i.complete,natural:[i.naturalWidth,i.naturalHeight],...result})}return out}");
c.save('observations/E-064-image-readiness.json',assets);
await c.call('Emulation.clearDeviceMetricsOverride');await c.call('Emulation.setTouchEmulationEnabled',{enabled:false,maxTouchPoints:1});await c.call('Emulation.setEmulatedMedia',{features:[]});console.log('motion and asset readiness captured');
}finally{c.close()}
